### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by Fogha** [deviceinsight/iot-hubber#5]
i would like to update the docs for those of us who prefer Npm because honestly i have been at it for a while now, and `yarn install` keeps giving me tunnel errors

**Comment by VeronikaHillebrand** [comment]
Hi @Fogha - I'm reluctant to accept this PR and issue. The reason is that here we all work with yarn. To give people the option would mean maintaining a package-lock.json and also a yarn.lock file. This sounds like it could lead to inconsistencies so I would rather not. If you would like to contribute, feel free to use npm yourself privately.

**Comment by Fogha** [comment]
thats okay, makes a lot of sense
