### ISSUE TITLE
Replace the values for IOTHUB_URL and IOTHUB_BROKER with real data

### ISSUE THREAD

**Issue by nimitbhargava** [deviceinsight/iot-hubber#7]
I am trying to setup the project in local.
What does this line from [README](https://github.com/deviceinsight/iot-hubber/blob/master/README.md) means?
```
Replace the values for IOTHUB_URL and IOTHUB_BROKER with real data
```

**Comment by VeronikaHillebrand** [comment]
Hi there, in order to connect to the Azure IOT Hub, you need to enter the IOTHUB_URL and IOTHUB_BROKER here. You can find this data in the Azure IOT Hub, if you have a subscription.

Unfortunately, this makes it quite hard to contribute to pages "behind" the login screen if you have no Azure IOT Hub. However, for the purpose of Hacktoberfest, the issues should all be before the login happens.

So you can just choose dummy data.

Hope that helps!

**Comment by nimitbhargava** [comment]
@VeronikaHillebrand Sure, I will try some dummy data at IOTHUB_URL and IOTHUB_BROKER.
